export const INCREMENT_EHTHUSIASM = 'INCREMENT_ENTHUSIASM'
export type INCREMENT_EHTHUSIASM = typeof INCREMENT_EHTHUSIASM

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM'
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM