stages:
  - build
  - deploy

build:
  image: node:8.11
  stage: build
  script:
    - npm install --progress=false
    - npm install -g quasar-cli
    - quasar build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  only:
    - master

deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ gitlab@47.93.125.252:/var/www/html/public
    - echo 'deployed app successful'
  only:
    - master


# echo "$SSH_PRIVATE_KEY"
# 1 - ssh-key-gen : Generate ssh key on my local
# 2 - ssh-copy-id user@server : Copy public key to the server
# 3 - Create SSH_PRIVATE_KEY variable contains the private key on my local from Gitlab UI Dashboard


# echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
# Preventing yes/no popup when connect to the server